# Generated by Django 5.2.7 on 2026-03-22 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Female", "Female"),
                            ("Male", "Male"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            ("CRITICAL", "Critical"),
                            ("SCHEDULED", "Scheduled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lastVisit", models.DateField()),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacientes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialDiagnostico",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("summary", models.TextField()),
                ("date", models.DateField()),
                ("imageUrl", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[("REVIEWED", "Reviewed"), ("PENDING", "Pending")],
                        max_length=20,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosticos",
                        to="predictor.paciente",
                    ),
                ),
            ],
        ),
    ]
