# Generated by Django 5.2.7 on 2026-03-22 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0002_usuariomedico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="medico",
        ),
        migrations.AddField(
            model_name="paciente",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pacientes",
                to="predictor.usuariomedico",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paciente",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
